default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  smtp:
    address: <%= ENV["SMTP_ADDRESS"] %>
    user_name: <%= ENV["SMTP_USER_NAME"] %>
    password: <%= ENV["SMTP_PASSWORD"] %>
    port: <%= ENV["SMTP_PORT"] %>
  mailer_default_url: <%= ENV["MAILER_DEFAULT_URL"] %>
  frontend_url: <%= ENV["FRONTEND_URL"] %>
  active_admin_namespace: <%= ENV["ACTIVE_ADMIN_NAMESPACE"] || "admin" %>

development:
  <<: *default

test:
  <<: *default
  mailer_default_url: "MAILER_DEFAULT_URL"
  frontend_url: "FRONTEND_URL"

staging:
  <<: *default

production:
  <<: *default
