default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  smtp:
    address: <%= ENV["SMTP_ADDRESS"] %>
    user_name: <%= ENV["SMTP_USER_NAME"] %>
    password: <%= ENV["SMTP_PASSWORD"] %>
    port: <%= ENV["SMTP_PORT"] %>
  mailer_default_url: <%= ENV["MAILER_DEFAULT_URL"] %>

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
